export type YahooMap = {
  [key: number]: {
    icon: string;
  };
};

const YAHOO_MAP: YahooMap = {
  0: { icon: 'tornado' },
  1: { icon: 'day-storm-showers' },
  2: { icon: 'hurricane' },
  3: { icon: 'thunderstorm' },
  4: { icon: 'thunderstorm' },
  5: { icon: 'rain-mix' },
  6: { icon: 'rain-mix' },
  7: { icon: 'rain-mix' },
  8: { icon: 'hail' },
  9: { icon: 'showers' },
  10: { icon: 'hail' },
  11: { icon: 'showers' },
  12: { icon: 'showers' },
  13: { icon: 'snow' },
  14: { icon: 'day-snow' },
  15: { icon: 'snow-wind' },
  16: { icon: 'snow' },
  17: { icon: 'hail' },
  18: { icon: 'rain-mix' },
  19: { icon: 'dust' },
  20: { icon: 'fog' },
  21: { icon: 'windy' },
  22: { icon: 'smoke' },
  23: { icon: 'strong-wind' },
  24: { icon: 'strong-wind' },
  25: { icon: 'snowflake-cold' },
  26: { icon: 'cloudy' },
  27: { icon: 'night-cloudy' },
  28: { icon: 'day-cloudy' },
  29: { icon: 'night-cloudy' },
  30: { icon: 'day-cloudy' },
  31: { icon: 'night-clear' },
  32: { icon: 'day-sunny' },
  33: { icon: 'night-partly-cloudy' },
  34: { icon: 'day-sunny-overcast' },
  35: { icon: 'rain-mix' },
  36: { icon: 'hot' },
  37: { icon: 'day-storm-showers' },
  38: { icon: 'day-storm-showers' },
  39: { icon: 'day-storm-showers' },
  40: { icon: 'showers' },
  41: { icon: 'snow-wind' },
  42: { icon: 'snow' },
  43: { icon: 'snow-wind' },
  44: { icon: 'day-sunny-overcast' },
  45: { icon: 'day-storm-showers' },
  46: { icon: 'snow' },
  47: { icon: 'day-storm-showers' },
  3200: { icon: 'stars' },
};

export default YAHOO_MAP;
